package MobileWebLocators;

import org.openqa.selenium.By;

public class GCV {

	public static By UserName=By.xpath("//input[@id='txtUserName']");
	public static By Password=By.xpath("//input[@id='txtPassword']");
	public static By Login=By.xpath("//button[contains(text(),'LOGIN')]");
	public static By Menu=By.xpath("//img[@alt='Menu btn logos']");
	public static By Motor=By.xpath("//span[@class='iconMenu motor']");
	public static By GCV=By.xpath("(//label[contains(text(),'GCV')])[1]");
	public static By Quote=By.xpath("//label[@for='quote']");
	public static By Policy=By.xpath("//label[@for='policy']");
	public static By Package=By.xpath("//label[@for='Packagett']");
	public static By Liability=By.xpath("//label[@for='Liabilitytt']");
	public static By A1_Pack=By.xpath("//label[contains(text(),'Motor GCV A1 - PKG Public Other than 3W')]");
	public static By A2_Pack=By.xpath("//label[contains(text(),'Motor GCV A2 - PKG Private Other than 3W')]");
	public static By A3_Pack=By.xpath("//label[contains(text(),'Motor GCV A3 - PKG 3W Public Carrier')]");
	public static By A4_Pack=By.xpath("//label[contains(text(),'Motor GCV A4 - PKG 3W Private Carrier')]");
	public static By A1_Liab=By.xpath("//label[contains(text(),'Motor GCV A1 - LIAB Public Other than 3W')]");
	public static By A2_Liab=By.xpath("//label[contains(text(),'Motor GCV A2 - LIAB Private Other than 3W')]");
	public static By A3_Liab=By.xpath("//label[contains(text(),'Motor GCV A3 - LIAB 3W Public Carrier')]");
	public static By A4_Liab=By.xpath("//label[contains(text(),'Motor GCV A4 - LIAB 3W Private Carrier')]");	
	public static By New=By.xpath("//label[@for='new']");
	public static By Renewal=By.xpath("//label[@for='renewal']");
	public static By Roll_Over=By.xpath("//label[@for='rollover']");
	public static By Used=By.xpath("//label[@for='used']");
	public static By Model=By.xpath("//input[@id='modelVariantFeild']");
	public static By Mahindra=By.xpath("//label[contains(text(),'MAHINDRA')]");
	public static By Pack_Suggestion=By.xpath("//li[contains(@id,'MAHINDRA | BOLERO | DX |')]");
	public static By A2_Pack_Suggestion=By.xpath("//li[contains(text(),'MAHINDRA | BOLERO | CAMPER')]");
	public static By A3_Pack_Suggestion=By.xpath("//li[contains(text(),'MAHINDRA | ALFA |')]");
	public static By Fuel_Type=By.xpath("//select[@id='TypeOfFuelVehicle']");
	public static By RTO=By.xpath("//input[@id='rtoLocationFeild']");
	public static By Mumbai=By.xpath("//div[@class='MUMBAI']");
	public static By MH_01=By.xpath("//li[contains(text(),' MH-01')]");
	public static By Calculate_Premium=By.xpath("//button[contains(text(),'CALCULATE PREMIUM')]");
	public static By Convert=By.xpath("//div[contains(text(),'Convert')]");
	public static By Sourcing_Info=By.xpath("(//div[contains(@class,'agent-icon')])[1]");
	public static By Cust_1=By.xpath("//input[@id='IdDynamicControl0']");
	public static By Cust_2=By.xpath("//input[@id='IdDynamicControl1']");
	public static By Save=By.xpath("(//button[contains(text(),'Save')])[1]");
	public static By DOB=By.xpath("//input[@id='DPDateOfBirth']");
	public static By Year=By.xpath("//select[@class='ui-datepicker-year']");
	public static By Month=By.xpath("//select[@class='ui-datepicker-month']");
	public static By Date=By.xpath("(//a[contains(text(),'1')])[1]");
	public static By Pan_No=By.xpath("(//input[@id='txtPanNumber'])[1]");
	public static By Verify_Pan=By.xpath("//input[@id='btnVerifyPan']");
	public static By Customer_Page=By.xpath("//div[@id='txtCustomerName']");
	public static By Marital_Status=By.xpath("//select[@id='ddlMaritalStatus']");
	public static By Continue=By.xpath("(//button[contains(text(),'Continue')])[1]");
	public static By Mobile_Number=By.xpath("//input[@id='txtMobileNumber']");
	public static By Continue_1=By.xpath("//button[@onclick='submitcustomerDetails()']");
	public static By Vehicle_Details=By.xpath("//button[@id='nextBtnBottom']");
	public static By Engine_Number=By.xpath("//input[@id='EngineNumberVehicle']");
	public static By Chassis_Number=By.xpath("//input[@id='ChasisNumberVehicle']");
	public static By Vehicle_Type=By.xpath("//select[@id='DpGCVTypeOfVehicleID']");
	public static By Goods_Type=By.xpath("//select[@id='DpGCVSUBTypeOfVehicle']");
	public static By Get_Cover_Details=By.xpath("//button[@id='nextBtnBottom']");
	public static By Additional_Cover=By.xpath("//div[@id='additionalCover']");
	public static By NomineeName=By.xpath("//input[@id='txtPAOwnerCoverNomineeName']");
	public static By NomineeAge=By.xpath("//input[@id='txtNomineeAge']");
	public static By NomineeRelationship=By.xpath("//select[@id='Nominee_RelationshipOwnerDriver']");
	public static By Continue_NominnePage=By.xpath("//button[@id='getCoversContinue']");
	public static By OtherDetails=By.xpath("//button[@id='nextBtnBottom']");
	public static By InspectionDetails=By.xpath("//button[@id='nextBtnBottom']");
	public static By CalculatePremium_1=By.xpath("//button[@id='nextBtnBottom']");
	public static By Submit=By.xpath("//button[@onclick='SaveInformation()']");
	public static By SuccessMessage=By.xpath("//label[contains(text(),'Success Message')]");
}
